inherit_from: configs/replica/replica.yaml

back_end:
  bound: [[-6.7,5.1],[-7.5,4.9],[-2.8,3.5]]
  # marching_cubes_bound: [[-6.7,5.1],[-7.5,4.9],[-2.8,3.5]]
  # bound: [[-5.3,3.7],[-6.1,3.4],[-1.4,2.0]]
  marching_cubes_bound: [[-5.2,3.6],[-6.0,3.3],[-1.3,1.9]]

scene: office_3