inherit_from: configs/replica/replica.yaml

back_end:
  bound: [[-5.0,4.6],[-4.4,6.9],[-2.8,3.1]]
  # marching_cubes_bound: [[-5.0,4.6],[-4.4,6.9],[-2.8,3.1]]
  # bound: [[-3.6,3.2],[-3.0,5.5],[-1.4,1.7]]
  marching_cubes_bound: [[-3.5,3.1],[-2.9,5.4],[-1.3,1.6]]

scene: office_2